package com.bms.show.entity;

import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.bms.show.util.Genre;
import com.bms.show.util.GenreListConverter;
import com.bms.show.util.Language;
import com.bms.show.util.LanguageListConverter;

@DynamoDBTable(tableName = "Movies")
public class Movie {

	@Id
	private String movieId;
	@DynamoDBAttribute
	private String movieName;
	@DynamoDBAttribute
	private double rating;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LanguageListConverter.class)
	private List<Language> languages;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = GenreListConverter.class)
	private List<Genre> genre;
	@DynamoDBAttribute
	private List<String> actors;
	@DynamoDBAttribute
	private int releaseYear;

	/**
	 * 
	 */
	public Movie() {
		super();
	}

	/**
	 * @param movieId
	 * @param movieName
	 * @param rating
	 * @param languages
	 * @param genre
	 * @param actors
	 * @param releaseYear
	 */
	public Movie(String movieId, String movieName, double rating, List<Language> languages, List<Genre> genre,
			List<String> actors, int releaseYear) {
		super();
		this.movieId = movieId;
		this.movieName = movieName;
		this.rating = rating;
		this.languages = languages;
		this.genre = genre;
		this.actors = actors;
		this.releaseYear = releaseYear;
	}

	/**
	 * @return the movieId
	 */
	@DynamoDBHashKey(attributeName = "movieId")
	@DynamoDBAutoGeneratedKey
	public String getMovieId() {
		return movieId;
	}

	/**
	 * @param movieId the movieId to set
	 */
	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	/**
	 * @return the movieName
	 */
	public String getMovieName() {
		return movieName;
	}

	/**
	 * @param movieName the movieName to set
	 */
	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	/**
	 * @return the rating
	 */
	public double getRating() {
		return rating;
	}

	/**
	 * @param rating the rating to set
	 */
	public void setRating(double rating) {
		this.rating = rating;
	}

	/**
	 * @return the languages
	 */
	public List<Language> getLanguages() {
		return languages;
	}

	/**
	 * @param languages the languages to set
	 */
	public void setLanguages(List<Language> languages) {
		this.languages = languages;
	}

	/**
	 * @return the genre
	 */
	public List<Genre> getGenre() {
		return genre;
	}

	/**
	 * @param genre the genre to set
	 */
	public void setGenre(List<Genre> genre) {
		this.genre = genre;
	}

	/**
	 * @return the actors
	 */
	public List<String> getActors() {
		return actors;
	}

	/**
	 * @param actors the actors to set
	 */
	public void setActors(List<String> actors) {
		this.actors = actors;
	}

	/**
	 * @return the releaseYear
	 */
	public int getReleaseYear() {
		return releaseYear;
	}

	/**
	 * @param releaseYear the releaseYear to set
	 */
	public void setReleaseYear(int releaseYear) {
		this.releaseYear = releaseYear;
	}

}
