package com.bms.show.entity;

import java.time.LocalTime;
import java.time.LocalDate;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.bms.show.util.Language;
import com.bms.show.util.LanguageConverter;
import com.bms.show.util.LocalDateConverter;
import com.bms.show.util.LocalTimeConverter;

@DynamoDBTable(tableName = "Shows")
public class Show {

	@Id
	private String showId;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LocalTimeConverter.class)
	private LocalTime startTime;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LocalTimeConverter.class)
	private LocalTime endTime;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LocalDateConverter.class)
	private LocalDate showDate;

	@DynamoDBAttribute
	private String movieId;

	@DynamoDBAttribute
	private int screenId;

	@DynamoDBAttribute
	private String theaterId;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LanguageConverter.class)
	private Language language;

	/**
	 * 
	 */
	public Show() {
		super();
	}

	/**
	 * @param showId
	 * @param startTime
	 * @param endTime
	 * @param showDate
	 * @param movieId
	 * @param screenId
	 * @param theaterId
	 * @param language
	 */
	public Show(String showId, LocalTime startTime, LocalTime endTime, LocalDate showDate, String movieId, int screenId,
			String theaterId, Language language) {
		super();
		this.showId = showId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.showDate = showDate;
		this.movieId = movieId;
		this.screenId = screenId;
		this.theaterId = theaterId;
		this.language = language;
	}

	/**
	 * @return the showId
	 */
	@DynamoDBHashKey(attributeName = "showId")
	@DynamoDBAutoGeneratedKey
	public String getShowId() {
		return showId;
	}

	/**
	 * @param showId the showId to set
	 */
	public void setShowId(String showId) {
		this.showId = showId;
	}

	/**
	 * @return the startTime
	 */
	public LocalTime getStartTime() {
		return startTime;
	}

	/**
	 * @param startTime the startTime to set
	 */
	public void setStartTime(LocalTime startTime) {
		this.startTime = startTime;
	}

	/**
	 * @return the endTime
	 */
	public LocalTime getEndTime() {
		return endTime;
	}

	/**
	 * @param endTime the endTime to set
	 */
	public void setEndTime(LocalTime endTime) {
		this.endTime = endTime;
	}

	/**
	 * @return the showDate
	 */
	public LocalDate getShowDate() {
		return showDate;
	}

	/**
	 * @param showDate the showDate to set
	 */
	public void setShowDate(LocalDate showDate) {
		this.showDate = showDate;
	}

	/**
	 * @return the movieId
	 */
	public String getMovieId() {
		return movieId;
	}

	/**
	 * @param movieId the movieId to set
	 */
	public void setMovieId(String movieId) {
		this.movieId = movieId;
	}

	/**
	 * @return the screenId
	 */
	public int getScreenId() {
		return screenId;
	}

	/**
	 * @param screenId the screenId to set
	 */
	public void setScreenId(int screenId) {
		this.screenId = screenId;
	}

	/**
	 * @return the theaterId
	 */
	public String getTheaterId() {
		return theaterId;
	}

	/**
	 * @param theaterId the theaterId to set
	 */
	public void setTheaterId(String theaterId) {
		this.theaterId = theaterId;
	}

	/**
	 * @return the language
	 */
	public Language getLanguage() {
		return language;
	}

	/**
	 * @param language the language to set
	 */
	public void setLanguage(Language language) {
		this.language = language;
	}

}
