package com.theatres.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.List;

@DynamoDBTable(tableName = "City")
public class City {

    private String cityId;
    private String cityName;
    private String state;
    private List<String> theatreIds; // List of theater IDs

    // Getter and Setter for cityId
    @DynamoDBHashKey(attributeName = "cityId")
    public String getCityId() {
        return cityId;
    }

    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    // Getter and Setter for cityName
    @DynamoDBAttribute(attributeName = "cityName")
    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    // Getter and Setter for state
    @DynamoDBAttribute(attributeName = "state")
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    // Getter and Setter for theatreIds
    @DynamoDBAttribute(attributeName = "theatreIds")
    public List<String> getTheatreIds() {
        return theatreIds;
    }

    public void setTheatreIds(List<String> theatreIds) {
        this.theatreIds = theatreIds;
    }
}

