package com.theatres.model;

import org.springframework.data.annotation.Id;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Screen")
public class Screen {
   // @Id
   // @DynamoDBAutoGeneratedKey
    private String screenId;

    @DynamoDBAttribute
    private String screenName;

    private String theatreId; // Add theatreId property

    public Screen() {
        // Default constructor is required by Spring Data DynamoDB
    }

    public Screen(String screenName) {
        this.screenName = screenName;
    }
    @DynamoDBHashKey(attributeName = "screenId")
 //   @DynamoDBHashKey
    public String getScreenId() {
        return screenId;
    }

    public void setScreenId(String screenId) {
        this.screenId = screenId;
    }

    @DynamoDBAttribute
    public String getScreenName() {
        return screenName;
    }

    public void setScreenName(String screenName) {
        this.screenName = screenName;
    }

    // Getter and setter for theatreId
    @DynamoDBAttribute
    public String getTheatreId() {
        return theatreId;
    }

    public void setTheatreId(String theatreId) {
        this.theatreId = theatreId;
    }
}

