package com.theatres.model;

import java.util.List;

import org.springframework.data.annotation.Id;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.util.List;

@DynamoDBTable(tableName = "Theatre")
public class Theatre {

    private String theatreId;
    private String theatreName;
    private String cityId;
    private String address;
    private List<String> screenIds; // List of screen IDs

    // Getter and Setter for theatreId
    @DynamoDBHashKey(attributeName = "theatreId")
    public String getTheatreId() {
        return theatreId;
    }

    public void setTheatreId(String theatreId) {
        this.theatreId = theatreId;
    }

    // Getter and Setter for theatreName
    @DynamoDBAttribute(attributeName = "theatreName")
    public String getTheatreName() {
        return theatreName;
    }

    public void setTheatreName(String theatreName) {
        this.theatreName = theatreName;
    }

    // Getter and Setter for cityId
    @DynamoDBAttribute(attributeName = "cityId")
    public String getCityId() {
        return cityId;
    }

    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    // Getter and Setter for address
    @DynamoDBAttribute(attributeName = "address")
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    // Getter and Setter for screenIds
    @DynamoDBAttribute(attributeName = "screenIds")
    public List<String> getScreenIds() {
        return screenIds;
    }

    public void setScreenIds(List<String> screenIds) {
        this.screenIds = screenIds;
    }
}
